const Types = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  CLEAR_USER: 'CLEAR_USER',
  SAVE_ACCOUNT: 'SAVE_ACCOUNT',
  CLEAR_ACCOUNT: 'CLEAR_ACCOUNT',
  LIST_NEW_ORDER: 'LIST_NEW_ORDER',
  LIST_PAYMENT: 'LIST_PAYMENT',
  LOGIN: 'LOGIN',
  SPLASH: 'SPLASH',
  LIST_PRODUCT: 'LIST_PRODUCT',
  LIST_MEDICINE: 'LIST_MEDICINE',
  CUSTOMER_INFO: 'CUSTOMER_INFO',
  INVOICE: 'INVOICE',
  LOG_OUT: 'LOG_OUT',
  RESET_INVOICE: 'RESET_INVOICE',
  ADD_PRODUCT_INVOICE:'ADD_PRODUCT_INVOICE',
  ADD_PRODUCT_FROM_API: 'ADD_PRODUCT_FROM_API',
  ADD_PRODUCT_FROM_API_LISTENER: 'ADD_PRODUCT_FROM_API_LISTENER'
};

export default Types